[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[build]
  publish = "."

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 